import { getAuthenticatedUser } from "@/lib/api/auth";
import { apiError,apiSuccess,mapDatabaseError,mapUnknownError } from "@/lib/api/response";
import { parseUuid,readJsonObject,RequestValidationError } from "@/lib/api/validation";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export async function GET(request:Request){try{const supabase=await createSupabaseServerClient();if(!await getAuthenticatedUser(supabase))return apiError("UNAUTHENTICATED","Bạn cần đăng nhập",401);const id=parseUuid(new URL(request.url).searchParams.get("contract_id"),"contract_id");const{data,error}=await supabase.from("room_monthly_revenues").select("*, room_revenue_cycles(*)").eq("contract_id",id).order("created_at");if(error)return mapDatabaseError(error);return apiSuccess(data??[])}catch(e){return mapUnknownError(e)}}

export async function POST(request:Request){try{const supabase=await createSupabaseServerClient();const user=await getAuthenticatedUser(supabase);if(!user)return apiError("UNAUTHENTICATED","Bạn cần đăng nhập",401);const body=await readJsonObject(request),contractId=parseUuid(body.contract_id,"contract_id"),month=integer(body.month,"month",1,12),year=integer(body.year,"year",2000,2200);
 const{data:contract,error:ce}=await supabase.from("rental_contracts").select("id,room_id,monthly_price,deposit_amount,rooms!inner(id,room_code,property_id),contract_tenants(role,tenants(full_name))").eq("id",contractId).single();if(ce)return mapDatabaseError(ce);const room=Array.isArray(contract.rooms)?contract.rooms[0]:contract.rooms;if(!room?.property_id)return apiError("CONFLICT","Hợp đồng chưa gắn tòa nhà",409);
 const{data:cycle,error:cycleError}=await supabase.from("room_revenue_cycles").upsert({property_id:room.property_id,month,year,created_by:user.id},{onConflict:"property_id,month,year",ignoreDuplicates:false}).select("*").single();if(cycleError)return mapDatabaseError(cycleError);
 const tenantRows=contract.contract_tenants??[];const representative=tenantRows.find((r)=>r.role==="Chủ hợp đồng")??tenantRows[0];const tenant=Array.isArray(representative?.tenants)?representative.tenants[0]:representative?.tenants;
 const fields=editable(body);const{data,error}=await supabase.from("room_monthly_revenues").insert({cycle_id:cycle.id,property_id:room.property_id,room_id:room.id,contract_id:contractId,created_by:user.id,...fields,room_code:fields.room_code??room.room_code,tenant_name:fields.tenant_name??tenant?.full_name??null}).select("*").single();if(error)return mapDatabaseError(error);return apiSuccess(data,201)
 }catch(e){return mapUnknownError(e)}}

export async function PATCH(request:Request){try{const supabase=await createSupabaseServerClient();if(!await getAuthenticatedUser(supabase))return apiError("UNAUTHENTICATED","Bạn cần đăng nhập",401);const body=await readJsonObject(request),id=parseUuid(body.revenue_id,"revenue_id");const{data,error}=await supabase.from("room_monthly_revenues").update(editable(body)).eq("id",id).select("*").single();if(error)return mapDatabaseError(error);return apiSuccess(data)}catch(e){return mapUnknownError(e)}}

function integer(value:unknown,name:string,min:number,max:number){const n=Number(value);if(!Number.isInteger(n)||n<min||n>max)throw new RequestValidationError(`${name} không hợp lệ`);return n}
function editable(body:Record<string,unknown>){const num=(key:string)=>{const n=Number(body[key]??0);if(!Number.isFinite(n)||n<0)throw new RequestValidationError(`${key} phải là số không âm`);return n};const text=(key:string,max:number)=>String(body[key]??"").trim().slice(0,max)||null;const start=num("electricity_start"),end=num("electricity_end");if(end<start)throw new RequestValidationError("Số điện cuối không được nhỏ hơn số điện đầu");return{room_code:text("room_code",100),tenant_name:text("tenant_name",300),deposit_amount:num("deposit_amount"),rent_amount:num("rent_amount"),electricity_start:start,electricity_end:end,electricity_unit_price:num("electricity_unit_price"),parking_fee:num("parking_fee"),service_fee:num("service_fee"),water_fee:num("water_fee"),other_fee:num("other_fee"),note:text("note",5000)}}
